/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scoring/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runScoring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["nonce"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LatLon: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        RouteInput: {
            start: components["schemas"]["LatLon"];
            end: components["schemas"]["LatLon"];
            waypoints: components["schemas"]["LatLon"][];
            /** Format: int32 */
            slot?: number;
            /** Format: int64 */
            routeId?: number;
        };
        Busiest: {
            slug: string;
            name: string;
            /** Format: int32 */
            points: number;
            /** Format: int32 */
            people: number;
            /** Format: int32 */
            rank: number;
        };
        RouteView: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            slot: number;
            name: string;
            start: components["schemas"]["LatLon"];
            end: components["schemas"]["LatLon"];
            waypoints: components["schemas"]["LatLon"][];
            out: number[][];
            back: number[][];
            /** Format: double */
            lengthOutM: number;
            /** Format: double */
            lengthBackM: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            busiest?: components["schemas"]["Busiest"];
        };
        Order: {
            routes: components["schemas"]["SlotAssignment"][];
        };
        SlotAssignment: {
            /** Format: int64 */
            routeId: number;
            /** Format: int32 */
            slot: number;
        };
        MyRoutes: {
            routes: components["schemas"]["RouteView"][];
            slots: components["schemas"]["SlotView"][];
            /** Format: date-time */
            countsFrom: string;
        };
        SlotView: {
            /** Format: int32 */
            slot: number;
            /** Format: date-time */
            lockedUntil?: string;
            /** Format: date-time */
            graceUntil?: string;
        };
        Preview: {
            points: components["schemas"]["LatLon"][];
            out: number[][];
            back: number[][];
            backLeaves: number[][][];
            backVia: string[];
            /** Format: double */
            lengthOutM: number;
            /** Format: double */
            lengthBackM: number;
            name: string;
            problems: components["schemas"]["Problem"][];
        };
        Problem: {
            /** @enum {string} */
            code: "SIDE_ROAD" | "NO_ROAD_NEARBY" | "NO_ROUTE" | "NO_WAY_BACK" | "TOO_LONG" | "OVERLAP" | "SLOT_LOCKED" | "SLOTS_FULL";
            point?: string;
            nearest?: components["schemas"]["LatLon"];
            /** Format: double */
            lengthM?: number;
            /** Format: double */
            limitM?: number;
            /** Format: int64 */
            routeId?: number;
            /** Format: int32 */
            slot?: number;
            routeName?: string;
            /** Format: date-time */
            until?: string;
        };
        GoogleSignIn: {
            credential: string;
        };
        Me: {
            /** Format: int64 */
            id: number;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            liveAt: string;
        };
        Run: {
            /** Format: date-time */
            at: string;
            /** Format: int32 */
            segments: number;
            /** Format: int32 */
            stretches: number;
            /** Format: int32 */
            ranked: number;
            /** Format: int32 */
            uploaded: number;
            /** Format: int32 */
            deleted: number;
            published: boolean;
            note: string;
        };
        Place: {
            name: string;
            kind: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        Nonce: {
            nonce: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteView"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRoutes"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRoutes"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteView"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
        };
    };
    google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runScoring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    nonce: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Nonce"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
