import type { LngLatBoundsLike } from 'maplibre-gl'
import data from './provinces.json'

// Generated by `python -m routerank_import provinces` from the OSM extract
export interface Province {
  name: string
  slug: string
  iso: string
  bbox: [number, number, number, number] // min lon, min lat, max lon, max lat
}

export const provinces = data as Province[]

export const DEFAULT_PROVINCE = 'western'

// The whole island with a margin; the map can't be panned beyond it
export const SRI_LANKA_BOUNDS: LngLatBoundsLike = [[78.9, 5.4], [82.6, 10.4]]

export function provinceBySlug(slug: string | undefined): Province | undefined {
  return provinces.find((p) => p.slug === slug)
}
