"""Write the Colombo fixture's import as a Flyway test migration for the backend's tests.

  .venv/Scripts/python -m tests.make_backend_fixture

Imports fixtures/colombo.osm.pbf into a throwaway PostGIS (Testcontainers), then writes its
import_run, road_segment and place rows as INSERTs to
backend/src/test/resources/db/testdata/V1000__colombo_roads.sql. The backend builds its test
GraphHopper graph from the same file, so the extract dates match. Re-run after changing the import.
"""

import os
from datetime import datetime, timezone
from pathlib import Path

import psycopg

from routerank_import.__main__ import extract_date_of, load

from .conftest import FIXTURE, migration_files

OUT = Path(__file__).parents[2] / "backend" / "src" / "test" / "resources" / "db" / "testdata" / "V1000__colombo_roads.sql"

TABLES = {
    "import_run": "id, extract_date, source_url, started_at, finished_at, segment_count",
    "road_segment": "id, import_run_id, osm_way_id, from_node, to_node, part, road_class, is_link, oneway, "
                    "oneway_bus, province, geom, length_m",
    "place": "id, import_run_id, osm_id, kind, name, geom",
}


def main() -> None:
    from testcontainers.community.postgres import PostgresContainer

    with PostgresContainer("postgis/postgis:16-3.5", driver=None) as pg:
        url = pg.get_connection_url()
        with psycopg.connect(url, autocommit=True) as conn:
            for path in migration_files():
                conn.execute(path.read_text())
        os.environ["DATABASE_URL"] = url
        date = extract_date_of(str(FIXTURE)) or datetime(2026, 10, 1, tzinfo=timezone.utc)
        load(str(FIXTURE), "test://colombo", date, expected_provinces=1)

        lines = ["-- Generated by data/tests/make_backend_fixture.py from data/fixtures/colombo.osm.pbf; do not edit.",
                 "-- Test-only Flyway migration: the Colombo roads and places the routing tests run on."]
        with psycopg.connect(url) as conn:
            for table, columns in TABLES.items():
                select = ", ".join(f"quote_nullable({c}::text)" for c in columns.split(", "))
                rows = conn.execute(f"SELECT concat_ws(', ', {select}) FROM {table} ORDER BY id").fetchall()
                lines.append(f"\nINSERT INTO {table} ({columns}) OVERRIDING SYSTEM VALUE VALUES")
                lines.append(",\n".join(f"({r[0]})" for r in rows) + ";")
                lines.append(f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), (SELECT max(id) FROM {table}));")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
